export const MANIFEST_URL     = './img/polrad/manifest.json';
export const CONFIG_URL       = './config/radar_config.json';
export const PRODUCTS_URL     = './config/products.json';
export const PALETTES_URL     = './config/palettes.json';
export const PLAY_MS      = 800;
export const MAX_FRAMES   = 24;
export const REFRESH_MS   = 60 * 1000;
export const MAP_CENTER   = [52.1, 19.5];
export const MAP_ZOOM     = 6;
